# Generated by Django 5.1.7 on 2025-04-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteboardRoom',
            fields=[
                ('room_id', models.CharField(help_text='Unique identifier for the whiteboard room', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('state', models.BinaryField(blank=True, help_text='Serialized Yjs document state', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update')),
            ],
        ),
    ]
